import { polishFileContent } from '../../../utils';
import { CreateAppContext } from '../../../types';

export default ({ platforms }: CreateAppContext) =>
  polishFileContent(`
import Machinat, { makeContainer } from '@machinat/core';
import { build } from '@machinat/script';
import * as $ from '@machinat/script/keywords';
import WithYesNoReplies from '../components/WithYesNoReplies'
import useIntent from '../services/useIntent'

type AboutVars = {
  isOk: boolean;
};

export default build<AboutVars>(
  {
    name: 'About',
    initVars: () => ({ isOk: true }),
  },
  <$.BLOCK<AboutVars>>
    {() => (
      <>
        <p>
          I'm generated by Machinat.js framework
          <br />
          https://machinat.com
        </p>
        <WithYesNoReplies>Do you need more information?</WithYesNoReplies>
      </>
    )}
    
    <$.PROMPT<AboutVars>
      key="ask-more"
      set={
        makeContainer({ deps: [useIntent] })(
          (getIntent) => async (_, { event }) => {
            const intent = await getIntent(event);
            return { isOk: intent.type !== 'no' }
          }
        )
      }
    />
    
    <$.IF<AboutVars> condition={({ vars }) => !vars.isOk }>
      <$.THEN>
        {() => <p>Thank you!</p>}
        <$.RETURN />
      </$.THEN>
    </$.IF>
    
    {() => (
      <>
        <p>
          If you are new to Machinat.js, start from the tutorial to build your
          first conversational app: 
          <br />
          https://machinat.com/docs/learn
        </p>
        <Machinat.Pause time={2000} />
        <p>
          After that you can find out more features and guides in the documents:
          <br />
          https://machinat.com/docs
        </p>
        <WithYesNoReplies>Do these informations help?</WithYesNoReplies>
      </>
    )}

    <$.PROMPT<AboutVars>
      key="ask-feedback"
      set={
        makeContainer({ deps: [useIntent] })(
          (getIntent) => async (_, { event }) => {
            const intent = await getIntent(event);
            return { isOk: intent.type !== 'no' }
          }
        )
      }
    />

    {({ vars }) => 
      vars.isOk 
        ? (
          <p>
            Thank you! Follow us to get more info:<br />
            GitHub<br />
            https://github.com/machinat/machinat<br />
            Twitter<br />
            https://twitter.com/machinat
          </p>
        ) : (
          <p>
            Please help us to do better!<br />
            Open a discussion<br />
            https://github.com/machinat/machinat/discussions<br />
            Report an issue<br />
            https://github.com/machinat/machinat/issues/new
          </p>
        )
    }
  </$.BLOCK>
);
`);
