import { when, polishFileContent } from '../templateHelper';
import { CreateAppContext } from '../types';

export default ({ platforms, projectName }: CreateAppContext) =>
  polishFileContent(`
# ${projectName}

This is a Machinat chat app generated by [\`@machinat/creat-app\`](https://github.com/machinat/machinat/tree/master/packages/create-app).

Chat platforms supported by this app:${when(platforms.includes('messenger'))`
- [Messenger](https://messenger.com)`}${when(platforms.includes('telegram'))`
- [Telegram](https://telegram.org)`}${when(platforms.includes('line'))`
- [LINE](https://line.me)`}

## Getting Started

Run the app in development mode:

\`\`\`sh
$ npm run dev
\`\`\`

> For the first time using, you have to finish the setup steps listed at
> [Environments Setup](#environments-setup) first.

The command do 2 things:
1. Start a dev server up. It would automatically refresh when codes changed.
2. Create a https tunnel connected to a _https://xxx.t.machinat.dev_ endpoint.
   So your local server can accept webhook requests from the chat platforms.

### Environments Setup

#### Configure Chat Platforms

You need to manually setup the chat platforms to connect with. Check the
\`.env.example\` file for the required data and references. Fill them in the
\`.env\` file.

#### Start Dev Server

Try starting the server up with \`npm run dev\` command. It should be
successful if you fill all the required environments in previous step.

#### Initiate the Bindings

Keep the dev server runnning, and execute this command in a new command line
tab:

\`\`\`sh
$ npm run migrate
\`\`\`

This register the webhook bindings and some settings to the chat platforms.
Check \`src/migrations/0-init-app.ts\` file for the details.

You can run \`npm run migrate -- --down\` to revert the changes. It's useful if
you edit any settings and need to execute the migration jobs again.

#### Start Developing

Now go to the chat platforms and talk to your bot. Your hello world app should
be running! Edit the reply content in \`src/main.ts\` and the app will be
updated automatically.

## Learn More

Here are some resources to learn developing a chat app with Machinat:

- [Machinat Document](https://machinat.com/doc) - features and guides of Machinat framework.
- [Learn Machinat](https://machinat.com/learn) - a step-by-step tutorial to make a todo app in chat.
`);
